name: build

on:
  workflow_call:

permissions:
  contents: write

jobs:
  build_wheels:
    name: build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, macos-13, ubuntu-latest, ubuntu-24.04-arm ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.8
            3.9
            3.10
            3.11
            3.12
            3.13

      - name: install dependencies
        run: python -m pip install -r requirements.txt

      - name: build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: rockblock-9704-python-${{ matrix.os }}
          path: wheelhouse/*
          retention-days: 3
          overwrite: true
