name: publish

on:
  workflow_call:

jobs:
  publish:
    name: publish wheels to pypi
    runs-on: ubuntu-latest
    environment:
      name: Release
      url: https://pypi.org/p/rockblock9704
    permissions:
      contents: read
      id-token: write

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: combine
        run: |
          mkdir wheelhouse
          cp artifacts/**/*.whl wheelhouse/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
