name: publish

on:
  workflow_call:

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    name: publish wheels to pypi
    runs-on: ubuntu-latest
    environment:
      name: Release
      url: https://pypi.org/p/rockblock9704

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: combine
        run: |
          mkdir wheelhouse
          cp artifacts/**/*.whl wheelhouse/
        
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
